### ISSUE TITLE
ничего не понятно, но очень интересно 

### ISSUE THREAD

**Issue by sashaindrish** [win0err/solutions#1]
https://github.com/win0err/solutions/blob/f194737b2b1d100f3a2cab6a0ead034491255107/adventofcode/2021/01-sonar-sweep/input.txt#L1

**Comment by win0err** [comment]
Это (возможно, персональные) входные данные для задачи.

Задачи взяты с сайта https://adventofcode.com, где каждый год перед Новым годом игроки соревнуются (или просто разминают мозги) в решении задачек на алгоритмы и логику
